import React, { useState, useEffect, useRef, useCallback } from 'react';
import { 
  View, 
  StyleSheet, 
  FlatList, 
  Dimensions, 
  TouchableOpacity, 
  StatusBar, 
  ActivityIndicator, 
  Text, 
  Image,
  Animated,
  RefreshControl
} from 'react-native';
import { Video } from 'expo-av';
import * as Animatable from 'react-native-animatable';
import FeedHeader, { FEED_TYPES } from '../../components/feed/FeedHeader';
import VideoCaption from '../../components/feed/VideoCaption';
import VideoLoadingSpinner from '../../components/feed/VideoLoadingSpinner';
import HeartAnimation from '../../components/feed/HeartAnimation';
import FeedScrollIndicator from '../../components/feed/FeedScrollIndicator';
import { formatCount } from '../../utils/formatters';
import Ionicons from 'react-native-vector-icons/Ionicons';
import { useNavigation } from '@react-navigation/native';
import FeedVideoItem from '../../components/feed/FeedVideoItem';

// when we back we should handle first the fourth and the fith videos url, then update the feedscreen from the last file generated by claude for optimization//
const { width, height } = Dimensions.get('window');

// Mock video data
const mockVideos = [
  
  {
    id: '29',
    videoUrl: 'https://cdn.pixabay.com/video/2023/07/28/173530-849610807_large.mp4',
    thumbnailUrl: '',
    caption: 'Another cool video! #viral #dance',
    sound: { id: 's2', name: 'Popular Song' },
    likes: 5678,
    comments: 432,
    shares: 123,
    isLiked: false,
    user: {
      id: 'u2',
      username: 'creator2',
      avatarUrl: 'https://randomuser.me/api/portraits/women/32.jpg',
    }
  },
  {
    id: '31',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-waves-in-the-water-1164-large.mp4',
    thumbnailUrl: '',
    caption: 'Check out this amazing sunset! 🌅 #nature #sunset #views',
    sound: { id: 's3', name: 'Chill Vibes' },
    likes: 9245,
    comments: 278,
    shares: 112,
    isLiked: false,
    user: {
      id: 'u3',
      username: 'naturelover',
      avatarUrl: 'https://randomuser.me/api/portraits/women/45.jpg',
    }
  },

  {
    id: '14',
    videoUrl: 'https://cdn.pixabay.com/video/2023/02/09/149935-797511795_large.mp4',
    thumbnailUrl: '',
    caption: 'This is an awesome video! #fyp #trending',
    sound: { id: 's1', name: 'Original Sound' },
    likes: 1234,
    comments: 123,
    shares: 45,
    isLiked: false,
    user: {
      id: 'u1',
      username: 'creator1',
      avatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    }
  },
  {
    id: '17',
    videoUrl: 'https://cdn.pixabay.com/video/2023/07/28/173530-849610807_large.mp4',
    thumbnailUrl: '',
    caption: 'Another cool video! #viral #dance',
    sound: { id: 's2', name: 'Popular Song' },
    likes: 5678,
    comments: 432,
    shares: 123,
    isLiked: false,
    user: {
      id: 'u2',
      username: 'creator2',
      avatarUrl: 'https://randomuser.me/api/portraits/women/32.jpg',
    }
  },
  {
    id: '18',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-waves-in-the-water-1164-large.mp4',
    thumbnailUrl: '',
    caption: 'Check out this amazing sunset! 🌅 #nature #sunset #views',
    sound: { id: 's3', name: 'Chill Vibes' },
    likes: 9245,
    comments: 278,
    shares: 112,
    isLiked: false,
    user: {
      id: 'u3',
      username: 'naturelover',
      avatarUrl: 'https://randomuser.me/api/portraits/women/45.jpg',
    }
  },
 

  {
    id: '10',
    videoUrl: 'https://cdn.pixabay.com/video/2023/02/09/149935-797511795_large.mp4',
    thumbnailUrl: '',
    caption: 'This is an awesome video! #fyp #trending',
    sound: { id: 's1', name: 'Original Sound' },
    likes: 1234,
    comments: 123,
    shares: 45,
    isLiked: false,
    user: {
      id: 'u1',
      username: 'creator1',
      avatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    }
  },
 
  {
    id: '8',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-waves-in-the-water-1164-large.mp4',
    thumbnailUrl: '',
    caption: 'Check out this amazing sunset! 🌅 #nature #sunset #views',
    sound: { id: 's3', name: 'Chill Vibes' },
    likes: 9245,
    comments: 278,
    shares: 112,
    isLiked: false,
    user: {
      id: 'u3',
      username: 'naturelover',
      avatarUrl: 'https://randomuser.me/api/portraits/women/45.jpg',
    }
  },
];

const FeedScreen = () => {
  const [activeTab, setActiveTab] = useState(FEED_TYPES.FOR_YOU);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [videos, setVideos] = useState([]);
  const [videoLoading, setVideoLoading] = useState({});
  const [showHeartAnimation, setShowHeartAnimation] = useState({});
  
  const navigation = useNavigation();
  
  // Animated value for scroll position
  const scrollY = useRef(new Animated.Value(0)).current;
  
  // Reference for tracking scroll momentum
  const scrollMomentum = useRef({
    velocity: 0,
    position: 0,
    time: 0
  });
  
  // Track last tap time for double tap detection
  const lastTapTimeRef = useRef({});

  const flatListRef = useRef(null);
  const videoRefs = useRef({});

  // Load videos when component mounts
  useEffect(() => {
    loadVideos();
  }, []);

  // Load videos function (initial or refresh)
  const loadVideos = (isRefreshing = false) => {
    if (isRefreshing) {
      setRefreshing(true);
    } else {
      setLoading(true);
    }
    
    // Simulate API call with random delay for more realistic behavior
    setTimeout(() => {
      if (isRefreshing) {
        // For refresh, let's add a new video at the top (in real app, fetch new videos)
        const refreshedVideos = [...mockVideos];
        // Shuffle the array to simulate new content
        refreshedVideos.sort(() => Math.random() - 0.5);
        setVideos(refreshedVideos);
        setRefreshing(false);
        
        // Reset to first video
        if (flatListRef.current) {
          flatListRef.current.scrollToIndex({ index: 0, animated: true });
        }
      } else {
        setVideos(mockVideos);
        setLoading(false);
      }
    }, isRefreshing ? 1500 : 1000); // Longer delay for refresh for UX
  };
  
  // Handle pull-to-refresh
  const handleRefresh = () => {
    loadVideos(true);
  };

  // Handle video loading state change
  const onVideoLoadStart = useCallback((videoId) => {
    setVideoLoading(prev => ({ ...prev, [videoId]: true }));
  }, []);

  // Handle video ready state
  const onVideoLoad = useCallback((videoId) => {
    setVideoLoading(prev => ({ ...prev, [videoId]: false }));
  }, []);

  // Handle playback errors
  const onVideoError = useCallback((videoId, error) => {
    console.error(`Error loading video ${videoId}:`, error);
    setVideoLoading(prev => ({ ...prev, [videoId]: false }));
  }, []);
  
  // Handle heart animation end
  const onHeartAnimationEnd = useCallback((videoId) => {
    setShowHeartAnimation(prev => ({ ...prev, [videoId]: false }));
  }, []);
  
  // Handle like action
  const handleLikeVideo = useCallback((videoId, doubleTap = false) => {
    // Update videos array to toggle like status
    setVideos(prevVideos => 
      prevVideos.map(video => {
        if (video.id === videoId) {
          const newLikeStatus = !video.isLiked;
          return {
            ...video,
            isLiked: newLikeStatus,
            likes: newLikeStatus 
              ? video.likes + 1 
              : Math.max(0, video.likes - 1)
          };
        }
        return video;
      })
    );
    
    // If it's a double tap, show heart animation
    if (doubleTap) {
      setShowHeartAnimation(prev => ({ ...prev, [videoId]: true }));
    }
  }, []);
  
  // Handle single tap on video (for play/pause)
  const handleVideoTap = useCallback((videoId) => {
    const now = Date.now();
    const lastTap = lastTapTimeRef.current[videoId] || 0;
    const timeDiff = now - lastTap;
    
    // Check if this is a double tap (time difference less than 300ms)
    if (timeDiff < 300) {
      // Double tap detected
      handleLikeVideo(videoId, true);
    } else {
      // Single tap - toggle play/pause
      const videoRef = videoRefs.current[videoId];
      if (videoRef) {
        videoRef.getStatusAsync().then(status => {
          if (status.isPlaying) {
            videoRef.pauseAsync();
          } else {
            videoRef.playAsync();
          }
        });
      }
    }
    
    // Update last tap time
    lastTapTimeRef.current[videoId] = now;
  }, [handleLikeVideo]);

  // Handle scroll events to update animation values
  const handleScroll = Animated.event(
    [{ nativeEvent: { contentOffset: { y: scrollY } } }],
    { 
      useNativeDriver: false,
      listener: (event) => {
        // Track scroll momentum for better snapping
        const { y } = event.nativeEvent.contentOffset;
        const now = Date.now();
        const elapsed = now - scrollMomentum.current.time;
        
        if (elapsed > 0) {
          const delta = y - scrollMomentum.current.position;
          scrollMomentum.current.velocity = delta / elapsed;
          scrollMomentum.current.position = y;
          scrollMomentum.current.time = now;
        }
      }
    }
  );
  
  // Handle when scrolling ends to ensure proper snapping
  const handleScrollEnd = (event) => {
    const { y } = event.nativeEvent.contentOffset;
    const targetIndex = Math.round(y / height);
    
    // Apply momentum-based adjustment for better feel
    const velocity = scrollMomentum.current.velocity * 100;
    const momentum = Math.sign(velocity) * Math.min(Math.abs(velocity), 0.5);
    const adjustedIndex = Math.round(y / height + momentum);
    
    // Ensure index is within bounds
    const boundedIndex = Math.max(0, Math.min(adjustedIndex, videos.length - 1));
    
    // If we're not already perfectly positioned, scroll to the target index
    if (Math.abs(y - boundedIndex * height) > 2) {
      flatListRef.current?.scrollToOffset({
        offset: boundedIndex * height,
        animated: true,
      });
    }
    
    // Reset momentum tracking
    scrollMomentum.current = {
      velocity: 0,
      position: boundedIndex * height,
      time: Date.now(),
    };
  };

  // Handle video viewability change
  const onViewableItemsChanged = useRef(({ viewableItems }) => {
    if (viewableItems.length > 0) {
      const index = viewableItems[0].index;
      setCurrentIndex(index);

      // Pause all videos then play the current one
      Object.keys(videoRefs.current).forEach(key => {
        const videoRef = videoRefs.current[key];
        if (videoRef) {
          videoRef.pauseAsync();
        }
      });

      const currentVideoRef = videoRefs.current[viewableItems[0].item.id];
      if (currentVideoRef) {
        currentVideoRef.playAsync();
      }
    }
  }).current;

  // Configuration for viewability
  const viewabilityConfig = {
    itemVisiblePercentThreshold: 60, // Increased for better accuracy
  };

  // Handle tab change
  const handleTabChange = (tab) => {
    setActiveTab(tab);
    // In a real app, you would fetch different videos based on the tab
    // For now, just scroll back to top
    if (flatListRef.current) {
      flatListRef.current.scrollToIndex({ index: 0, animated: true });
      setCurrentIndex(0);
    }
  };

  // Render a single video item
  const renderItem = ({ item, index }) => {
    const isActive = index === currentIndex;
    const isVideoLoading = videoLoading[item.id];
    const isHeartAnimationVisible = showHeartAnimation[item.id] || false;

    return (
      <View style={styles.videoContainer}>
        <TouchableOpacity
          activeOpacity={1}
          style={styles.videoWrapper}
          onPress={() => handleVideoTap(item.id)}
        >
          <Video
            ref={ref => { videoRefs.current[item.id] = ref; }}
            source={{ uri: item.videoUrl }}
            style={styles.video}
            resizeMode="cover"
            shouldPlay={isActive}
            isLooping
            useNativeControls={false}
            onLoadStart={() => onVideoLoadStart(item.id)}
            onLoad={() => onVideoLoad(item.id)}
            onError={(error) => onVideoError(item.id, error)}
          />
          
          {/* Loading Spinner */}
          <VideoLoadingSpinner 
            isVisible={isVideoLoading} 
            size="medium" 
          />
          
          {/* Heart Animation */}
          <HeartAnimation
            isVisible={isHeartAnimationVisible}
            onAnimationEnd={() => onHeartAnimationEnd(item.id)}
            size="large"
          />
          
          {/* User Info Overlay */}
          <View style={styles.userInfoContainer}>
            <View style={styles.userInfo}>
              <TouchableOpacity style={styles.userProfileImageContainer}>
                <Image
                  source={{ uri: item.user.avatarUrl }}
                  style={styles.userProfileImage}
                />
              </TouchableOpacity>
              
              <Text style={styles.username}>@{item.user.username}</Text>
              
              <VideoCaption
                caption={item.caption}
                onHashtag={(hashtag) => console.log('Hashtag pressed:', hashtag)}
                onUserMention={(mention) => console.log('User mention pressed:', mention)}
              />
              
              {/* Sound Info */}
              <View style={styles.soundInfo}>
                <Text style={styles.soundText}>
                  {item.sound.name}
                </Text>
              </View>
            </View>
            
            {/* Action Buttons */}
            <View style={styles.actionButtons}>
              <TouchableOpacity 
                style={styles.actionButton}
                onPress={() => handleLikeVideo(item.id)}
              >
                <View style={styles.actionIconContainer}>
                  <Ionicons 
                    name={item.isLiked ? "heart" : "heart-outline"} 
                    size={28} 
                    color={item.isLiked ? "#FE2C55" : "#FFF"} 
                  />
                </View>
                <Text style={styles.actionText}>{formatCount(item.likes)}</Text>
              </TouchableOpacity>
              
              <TouchableOpacity 
                style={styles.actionButton}
                onPress={() => navigation.navigate('CommentsScreen', { videoId: item.id })}
              >
                <View style={styles.actionIconContainer}>
                  <Ionicons name="chatbubble-ellipses-outline" size={26} color="#FFF" />
                </View>
                <Text style={styles.actionText}>{formatCount(item.comments)}</Text>
              </TouchableOpacity>
              
              <TouchableOpacity style={styles.actionButton}>
                <View style={styles.actionIconContainer}>
                  <Ionicons name="share-outline" size={26} color="#FFF" />
                </View>
                <Text style={styles.actionText}>{formatCount(item.shares)}</Text>
              </TouchableOpacity>
            </View>
          </View>
        </TouchableOpacity>
      </View>
    );
  };

  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#FE2C55" />
        <Text style={styles.loadingText}>Loading awesome videos...</Text>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <StatusBar
        translucent
        backgroundColor="transparent"
        barStyle="light-content"
      />
      
      {/* Feed Header */}
      <FeedHeader
        activeTab={activeTab}
        onChangeTab={handleTabChange}
      />
      
      {/* Scroll Indicator */}
      <FeedScrollIndicator
        currentIndex={currentIndex}
        totalVideos={videos.length}
        scrollY={scrollY}
        height={height * 0.3}
      />
      
      {/* Video List */}
      <Animated.FlatList
        ref={flatListRef}
        data={videos}
        renderItem={renderItem}
        keyExtractor={(item) => item.id}
        pagingEnabled
        showsVerticalScrollIndicator={false}
        snapToInterval={height}
        snapToAlignment="start"
        decelerationRate="fast" // Use fast deceleration for snappier feel
        onViewableItemsChanged={onViewableItemsChanged}
        viewabilityConfig={viewabilityConfig}
        onScroll={handleScroll}
        onMomentumScrollEnd={handleScrollEnd}
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={handleRefresh}
            tintColor="#FE2C55"
            colors={["#FE2C55"]}
            progressBackgroundColor="#000"
            progressViewOffset={30} // Offset for header
          />
        }
        // Optimize FlatList performance
        removeClippedSubviews={true}
        maxToRenderPerBatch={3}
        windowSize={5}
        initialNumToRender={2}
        updateCellsBatchingPeriod={100}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#FFF',
    marginTop: 20,
  },
  videoContainer: {
    width,
    height,
  },
  videoWrapper: {
    flex: 1,
  },
  video: {
    flex: 1,
  },
  userInfoContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    padding: 20,
    paddingBottom: 40,
  },
  userInfo: {
    flex: 1,
    marginRight: 80,
  },
  userProfileImageContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: '#FFF',
  },
  userProfileImage: {
    width: 46,
    height: 46,
    borderRadius: 23,
  },
  username: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 5,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  soundInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  soundText: {
    color: '#FFF',
    fontSize: 14,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  actionButtons: {
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  actionButton: {
    alignItems: 'center',
    marginBottom: 15,
  },
  actionIconContainer: {
    width: 45,
    height: 45,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 5,
  },
  actionText: {
    color: '#FFF',
    fontSize: 12,
  },
});

export default FeedScreen;